services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
